### PR TITLE
Upgrade @studio/changes to v2.0.0

### PR DESCRIPTION
**Pull request by mroderick**
This PR upgrades `@studio/changes` to latest – `v2.0.0`

### CODE REVIEW

**Comment by mantoni** [comment]
Can we add the `--footer` and `--commits` flags as well?

**Review by mantoni — APPROVED** [review]
Thank you 🙌

**Comment by mroderick** [comment]
> Can we add the `--footer` and `--commits` flags as well?

I've replaced the commit with one that includes these

**Comment by mroderick** [comment]
I've published from `v1-maintenance` an interim version: `@studio/eslint-config@1.1.0`

**Pull request merged**
